apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-services
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: dashboard.MINIKUBE_IP.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 80

  - host: grafana.MINIKUBE_IP.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoring-grafana
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-services
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: europa.MINIKUBE_IP.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: europa
          servicePort: 80

  - host: jenkins.MINIKUBE_IP.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 80

  # - host: nginx.MINIKUBE_IP.xip.io
  #   http:
  #     paths:
  #     - path: /
  #       backend:
  #         serviceName: nginx
  #         servicePort: 80

  # - host: gogs.MINIKUBE_IP.xip.io
  #   http:
  #     paths:
  #     - path: /
  #       backend:
  #         serviceName: gogs
  #         servicePort: 80